version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@54.158.233.1 \
            "echo Start deploy && \
            cd ~/rahul-react-demo && \
            git pull origin master && \
            cp .env.example .env && \
            cd ~/ && \
            sudo docker compose up --build -d app && \
            echo Deploy end"
workflows:
  version: 2
  deploy_ec2:
    jobs:
      - build